name: Test Ci 

on:
  push:
    tags:
      - 'test*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build
        run: |
          npm install
          npm run build

      - name: Setup release files
        run: ./build.sh